# exclude: '^docs/|/migrations/|devcontainer.json'
exclude: '^docs'
default_stages: [commit]

default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-docstring-first
          - id: detect-private-key

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            args: ['--tab-width', '4', '--single-quote']
            # use python regex, https://github.com/mrmlnc/fast-glob#pattern-syntax, but here it use
            # https://pre-commit.com/#config-exclude_types
            # python regex
            exclude_types: ['markdown', 'html']

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.5
      hooks:
          - id: ruff
            args: [--config=pyproject.toml]
          - id: ruff-format
            args: [--config=pyproject.toml]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
